[aibox]
image=ghcr.io/askpng/aibox:latest
pull=true
replace=true
# links
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/conmon;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/flatpak;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/podman;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/xdg-open;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree;
init_hooks=ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/nvtop;
# additional packages & exports
exported_bins="/usr/bin/llama-lookup-stats"
exported_bins="/usr/bin/llama-tts"
exported_bins="/usr/bin/llama-quantize"
exported_bins="/usr/bin/llama-cli"
exported_bins="/usr/bin/llama-gen-docs"
exported_bins="/usr/bin/llama-passkey"
exported_bins="/usr/bin/llama-cvector-generator"
exported_bins="/usr/bin/llama-gguf-split"
exported_bins="/usr/bin/llama-gritlm"
exported_bins="/usr/bin/llama-batched-bench"
exported_bins="/usr/bin/llama-imatrix"
exported_bins="/usr/bin/llama-gguf-hash"
exported_bins="/usr/bin/llama-simple-chat"
exported_bins="/usr/bin/llama-tokenize"
exported_bins="/usr/bin/llama-batched"
exported_bins="/usr/bin/llama-speculative-simple"
exported_bins="/usr/bin/llama-bench"
exported_bins="/usr/bin/llama-embedding"
exported_bins="/usr/bin/llama-parallel"
exported_bins="/usr/bin/llama-lookup-create"
exported_bins="/usr/bin/llama-lookup-merge"
exported_bins="/usr/bin/llama-run"
exported_bins="/usr/bin/llama-gguf"
exported_bins="/usr/bin/llama-lookup"
exported_bins="/usr/bin/llama-llava-clip-quantize-cli"
exported_bins="/usr/bin/llama-perplexity"
exported_bins="/usr/bin/llama-eval-callback"
exported_bins="/usr/bin/llama-mtmd-cli"
exported_bins="/usr/bin/llama-simple"
exported_bins="/usr/bin/llama-server"
exported_bins="/usr/bin/llama-retrieval"
exported_bins="/usr/bin/llama-save-load-state"
exported_bins="/usr/bin/llama-export-lora"
exported_bins="/usr/bin/llama-lookahead"
exported_bins="/usr/bin/llama-speculative"
exported_bins="/usr/bin/llama-convert-llama2c-to-ggml"
